name: Build and Push Docker Dask-Flood-Mapper Dask Image

on:
  push:
    branches:
      - main
    #paths:
    #  - dask-flood-mapper-dask/dask.dockerfile  # Trigger on pushes to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Make sure buildx is used
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build and push image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dask-flood-mapper-dask:latest
          file: dask-flood-mapper-dask/dask.dockerfile
